#!/bin/bash

# TODO: Pull the relevant home directory from a .env file
USER=simon
GROUP=simon
WORKERS=25

NAME=assistance

HOME=/home/$USER
GIT_ROOT=$HOME/git/assistance
DATA_ROOT=$HOME/.assistance

VENV=$GIT_ROOT/.venv/bin/activate

BIND=unix:$DATA_ROOT/server/run/gunicorn.sock

WORKER_CLASS=uvicorn.workers.UvicornWorker
LOG_LEVEL=info

cd $GIT_ROOT
source $VENV

exec gunicorn assistance._api.main:app \
  --name $NAME \
  --workers $WORKERS \
  --worker-class $WORKER_CLASS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-
