#!/bin/bash

# TODO: Pull the relevant home directory from a .env file

NAME=chat-api
DIR=/home/simon/git/assistance
USER=simon
GROUP=simon
WORKERS=25
WORKER_CLASS=uvicorn.workers.UvicornWorker
VENV=$DIR/.venv/bin/activate
BIND=unix:$DIR/dev/run/gunicorn.sock
LOG_LEVEL=info

cd $DIR
source $VENV

exec gunicorn assistance._api.main:app \
  --name $NAME \
  --workers $WORKERS \
  --worker-class $WORKER_CLASS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-
