"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from _client.paths.chat_student_continue.post import (
    StudentChatContinueChatStudentContinuePost,
)
from _client.paths.chat_student_start.post import StudentChatStartChatStudentStartPost
from _client.paths.login.post import LoginForAccessTokenLoginPost
from _client.paths.query_from_transcript.post import SaveFormQueryFromTranscriptPost
from _client.paths.save_form.post import SaveFormSaveFormPost
from _client.paths.search_alphacrucis.post import (
    RunAlphacrucisSearchSearchAlphacrucisPost,
)
from _client.paths.send_signin_link.post import SendUserSigninLinkSendSigninLinkPost
from _client.paths.summarise_with_query_raw.post import (
    RunSummariseWithQueryRawSummariseWithQueryRawPost,
)
from _client.paths.summarise_with_query_url.post import (
    RunSummariseUrlWithQuerySummariseWithQueryUrlPost,
)
from _client.paths.temp_account.post import TempAccountTempAccountPost


class DefaultApi(
    LoginForAccessTokenLoginPost,
    RunAlphacrucisSearchSearchAlphacrucisPost,
    RunSummariseUrlWithQuerySummariseWithQueryUrlPost,
    RunSummariseWithQueryRawSummariseWithQueryRawPost,
    SaveFormQueryFromTranscriptPost,
    SaveFormSaveFormPost,
    SendUserSigninLinkSendSigninLinkPost,
    StudentChatContinueChatStudentContinuePost,
    StudentChatStartChatStudentStartPost,
    TempAccountTempAccountPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    pass
