"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import assistance._client
from assistance._client import api_client, configuration, schemas
from assistance._client.paths.temp_account import post  # noqa: E501

from .. import ApiTestMixin


class TestTempAccount(ApiTestMixin, unittest.TestCase):
    """
    TempAccount unit test stubs
        Temp Account  # noqa: E501
    """

    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = post.ApiForpost(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200


if __name__ == "__main__":
    unittest.main()
