import Head from "next/head";
import { Inter } from "@next/font/google";
import MoreInfo from "../components/MoreInfo";
import Hero from "../components/Hero";
import Reviews from "../components/Reviews";
import StudentExperience from "../components/StudentExperience";
import Navbar from "../components/NavBarEnrolment";
import Footer from "../components/Footer";
import Blog from "../components/Blog";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <MoreInfo />
      <Reviews />
      <StudentExperience />
      <Blog />
      <Footer />
    </>
  );
}
