"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import assistance._client
from assistance._client import configuration
from assistance._client.model.student_chat_continue_data import StudentChatContinueData


class TestStudentChatContinueData(unittest.TestCase):
    """StudentChatContinueData unit test stubs"""

    _configuration = configuration.Configuration()


if __name__ == "__main__":
    unittest.main()
