"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import _client
from _client import configuration
from _client.model.search_data import SearchData


class TestSearchData(unittest.TestCase):
    """SearchData unit test stubs"""

    _configuration = configuration.Configuration()


if __name__ == "__main__":
    unittest.main()
