"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import uuid  # noqa: F401
from datetime import date, datetime  # noqa: F401

import frozendict  # noqa: F401
import typing_extensions  # noqa: F401

from assistance._client import schemas  # noqa: F401


class StudentChatContinueData(schemas.DictSchema):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    class MetaOapg:
        required = {
            "client_text",
            "client_name",
        }

        class properties:
            client_name = schemas.StrSchema
            client_text = schemas.StrSchema
            __annotations__ = {
                "client_name": client_name,
                "client_text": client_text,
            }

    client_text: MetaOapg.properties.client_text
    client_name: MetaOapg.properties.client_name

    @typing.overload
    def __getitem__(
        self, name: typing_extensions.Literal["client_name"]
    ) -> MetaOapg.properties.client_name:
        ...

    @typing.overload
    def __getitem__(
        self, name: typing_extensions.Literal["client_text"]
    ) -> MetaOapg.properties.client_text:
        ...

    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema:
        ...

    def __getitem__(
        self,
        name: typing.Union[
            typing_extensions.Literal[
                "client_name",
                "client_text",
            ],
            str,
        ],
    ):
        # dict_instance[name] accessor
        return super().__getitem__(name)

    @typing.overload
    def get_item_oapg(
        self, name: typing_extensions.Literal["client_name"]
    ) -> MetaOapg.properties.client_name:
        ...

    @typing.overload
    def get_item_oapg(
        self, name: typing_extensions.Literal["client_text"]
    ) -> MetaOapg.properties.client_text:
        ...

    @typing.overload
    def get_item_oapg(
        self, name: str
    ) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]:
        ...

    def get_item_oapg(
        self,
        name: typing.Union[
            typing_extensions.Literal[
                "client_name",
                "client_text",
            ],
            str,
        ],
    ):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *args: typing.Union[
            dict,
            frozendict.frozendict,
        ],
        client_text: typing.Union[
            MetaOapg.properties.client_text,
            str,
        ],
        client_name: typing.Union[
            MetaOapg.properties.client_name,
            str,
        ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[
            schemas.AnyTypeSchema,
            dict,
            frozendict.frozendict,
            str,
            date,
            datetime,
            uuid.UUID,
            int,
            float,
            decimal.Decimal,
            None,
            list,
            tuple,
            bytes,
        ],
    ) -> "StudentChatContinueData":
        return super().__new__(
            cls,
            *args,
            client_text=client_text,
            client_name=client_name,
            _configuration=_configuration,
            **kwargs,
        )
